name: 📝 Task
description: Create a task for the team to work on, used internally only. We will delete tasks created by non-team members.
title: "[Task]: "
labels: [Task]
body:
- type: checkboxes
  attributes:
    label: Are you our team member?
    description: If you are not our team member, please go to discussions.
    options:
    - label: Yes, I am?
      required: true
- type: textarea
  attributes:
    label: SubTasks 
    placeholder: |
      - Sub Task 1
      - Sub Task 2
  validations:
    required: false
