name: Flutter Tag Build

on:
  workflow_dispatch:

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "1.2.3-2" 
